# English translations for PROJECT.
# Copyright (C) 2020 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2020.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2020-11-11 17:54+0300\n"
"PO-Revision-Date: 2020-11-04 17:05+0300\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: en\n"
"Language-Team: en <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.8.0\n"

#: core/actor_view.py:27 core/auth_view.py:113 core/auth_view.py:502
#: core/auth_view.py:629 core/auth_view.py:846 core/auth_view.py:1067
#: core/auth_view.py:1345 core/invite_link_view.py:27
#: core/permission_view.py:28 core/phantom_actor.py:35
#: core/phantom_actor.py:129 core/phantom_actor.py:186 core/socket_events.py:86
msgid "Invalid request data."
msgstr ""

#: core/actor_view.py:31 core/auth_view.py:119 core/auth_view.py:314
#: core/auth_view.py:529 core/auth_view.py:889 core/auth_view.py:902
#: core/auth_view.py:1225 core/auth_view.py:1320 core/permission_view.py:32
#: core/phantom_actor.py:39 core/socket_events.py:95
msgid "Signature verification failed."
msgstr ""

#: core/actor_view.py:66 core/permission_view.py:74
msgid "Some error occurred while creating actor."
msgstr ""

#: core/actor_view.py:71
msgid "Actor was successfully created."
msgstr ""

#: core/actor_view.py:106
msgid "Actor was successfully updated."
msgstr ""

#: core/actor_view.py:148
msgid "Actor was successfully deleted."
msgstr ""

#: core/auth_view.py:66 core/auth_view.py:74
msgid "Some error occurred while getting service info."
msgstr ""

#: core/auth_view.py:125
msgid ""
"There is no authentication token. Please try again or contact the "
"administrator."
msgstr ""

#: core/auth_view.py:133
msgid ""
"Invalid data in your authentication token. Please try again or contact "
"the administrator."
msgstr ""

#: core/auth_view.py:146 core/auth_view.py:971 core/auth_view.py:1186
msgid ""
"Some error occurred while creating actor. Please try again or contact the"
" administrator."
msgstr ""

#: core/auth_view.py:159
msgid ""
"Some error occurred while creating session token. Please try again or "
"contact the administrator."
msgstr ""

#: core/auth_view.py:163
msgid "Session token was successfully created."
msgstr ""

#: core/auth_view.py:203 core/auth_view.py:214
msgid "Unknown QR type. Please try again or contact the administrator."
msgstr ""

#: core/auth_view.py:224
msgid "There is no QR type. Please try again or contact the administrator."
msgstr ""

#: core/auth_view.py:232 core/auth_view.py:797
msgid ""
"Some error occurred while creating verification data. Please try again or"
" contact the administrator."
msgstr ""

#: core/auth_view.py:305
msgid "Unknown service."
msgstr ""

#: core/auth_view.py:340
#, python-format
msgid "There is no such groups %(invalid_groups)s"
msgstr ""

#: core/auth_view.py:349
msgid "Some error occurred with admin group."
msgstr ""

#: core/auth_view.py:355
msgid "This group can't be used by default for your service."
msgstr ""

#: core/auth_view.py:413
msgid ""
"Some error occurred while actor registration. Please contact the "
"administrator."
msgstr ""

#: core/auth_view.py:420 core/auth_view.py:437 core/auth_view.py:475
msgid "You are successfully registered."
msgstr ""

#: core/auth_view.py:445
msgid "Auth service is unreachable. Please try again or contact the administrator"
msgstr ""

#: core/auth_view.py:520 core/auth_view.py:1088
msgid ""
"There is no verification data based on received data. \n"
" Please get new QR code."
msgstr ""

#: core/auth_view.py:549 core/auth_view.py:660
msgid "Actor with such email already exists."
msgstr ""

#: core/auth_view.py:557 core/auth_view.py:652 core/auth_view.py:1351
msgid "Email you have inputted is invalid. Please check it."
msgstr ""

#: core/auth_view.py:563
msgid "There is no email in received data."
msgstr ""

#: core/auth_view.py:599
msgid ""
"Some error occurred while creating actor. Please try again or contact the"
" administrator"
msgstr ""

#: core/auth_view.py:645
msgid "Password and password confirmation do not match. Please check it."
msgstr ""

#: core/auth_view.py:669
msgid "Invalid request data type."
msgstr ""

#: core/auth_view.py:674
msgid "Invalid parameter email in optional data."
msgstr ""

#: core/auth_view.py:682
msgid "Invalid parameter password in optional data."
msgstr ""

#: core/auth_view.py:748
msgid "Some error occurred while creating actor. Please try again."
msgstr ""

#: core/auth_view.py:819
msgid "You are successfully receive your authentication token."
msgstr ""

#: core/auth_view.py:858
msgid ""
"There is no verification data based on received data. \n"
" Please get new QR code. "
msgstr ""

#: core/auth_view.py:870 core/auth_view.py:1105
msgid ""
"There is no your public key for your actor. Please contact the "
"administrator."
msgstr ""

#: core/auth_view.py:911
msgid "There is no such actor. Please contact the administrator"
msgstr ""

#: core/auth_view.py:917 core/auth_view.py:1136 core/auth_view.py:1164
#: core/auth_view.py:1278 core/auth_view.py:1390
msgid ""
"Auth service is unreachable. Please try again or contact the "
"administrator."
msgstr ""

#: core/auth_view.py:928
msgid ""
"Some error occurred with getting your authentication token. Please try "
"again or contact the administrator."
msgstr ""

#: core/auth_view.py:1001 core/auth_view.py:1074
msgid "Your authentication token is invalid. Please contact the administrator."
msgstr ""

#: core/auth_view.py:1010
msgid "There is no verification data based on received data."
msgstr ""

#: core/auth_view.py:1031
msgid "You are successfully authorized."
msgstr ""

#: core/auth_view.py:1116
msgid ""
"Your authentication token is invalid. Please try again or contact the "
"administrator."
msgstr ""

#: core/auth_view.py:1130 core/auth_view.py:1158 core/auth_view.py:1241
#: core/auth_view.py:1270 core/auth_view.py:1382
msgid "There is no such actor. Please try again or contact the administrator."
msgstr ""

#: core/auth_view.py:1146 core/auth_view.py:1175 core/auth_view.py:1259
#: core/auth_view.py:1289 core/auth_view.py:1400
msgid ""
"Your token expired and there is some error occurred while updating it. "
"Please try again or contact the administrator."
msgstr ""

#: core/auth_view.py:1200 core/auth_view.py:1302
msgid ""
"Some error occurred while creating session. Please try again or contact "
"the administrator."
msgstr ""

#: core/auth_view.py:1366
msgid "There is no actor with such email. Please check it."
msgstr ""

#: core/auth_view.py:1373
msgid "Password verification failed."
msgstr ""

#: core/auth_view.py:1428 core/invite_link_view.py:21
msgid "Invalid request type."
msgstr ""

#: core/auth_view.py:1444
msgid "Session token successfully saved."
msgstr ""

#: core/auth_view.py:1535
msgid "Some error has occurred, please contact the administrator"
msgstr ""

#: core/decorators.py:30 core/decorators.py:114 core/decorators.py:168
#: core/decorators.py:207
msgid "Actor have no session token."
msgstr ""

#: core/decorators.py:34 core/decorators.py:172 core/decorators.py:211
msgid "Actor have no session."
msgstr ""

#: core/decorators.py:45 core/decorators.py:177 core/decorators.py:216
msgid "Actor have no session or APT54."
msgstr ""

#: core/decorators.py:48
msgid "APT54 expired"
msgstr ""

#: core/decorators.py:54
msgid "Actor not found."
msgstr ""

#: core/decorators.py:60
msgid "Actor is banned."
msgstr ""

#: core/actions/phantom_actions.py:69 core/decorators.py:120
#: core/decorators.py:181 core/decorators.py:220
msgid "There is no such actor."
msgstr ""

#: core/decorators.py:124 core/decorators.py:190 core/decorators.py:226
#: core/decorators.py:244 core/decorators.py:252
msgid "Permissions denied."
msgstr ""

#: core/decorators.py:146 core/decorators.py:240
msgid "Unsupported Media Type."
msgstr ""

#: core/decorators.py:184 core/decorators.py:223
msgid "APT54 expired."
msgstr ""

#: core/exceptions.py:18
msgid "Database error."
msgstr ""

#: core/exceptions.py:31
msgid "Actor apt54 expired! You need update it."
msgstr ""

#: core/exceptions.py:39
msgid "Error with getting salt."
msgstr ""

#: core/exceptions.py:48
msgid "Error with getting apt54."
msgstr ""

#: core/exceptions.py:57
msgid "Error with getting session."
msgstr ""

#: core/exceptions.py:66
msgid "Invalid service class."
msgstr ""

#: core/exceptions.py:75
msgid "Auth service is unavailable."
msgstr ""

#: core/exceptions.py:93
msgid "Some error occurred with sending request."
msgstr ""

#: core/exceptions.py:103
msgid "Static group is missing."
msgstr ""

#: core/exceptions.py:113
msgid "Wrong service type."
msgstr ""

#: core/permission_view.py:103
msgid "Some error occurred while creating permissions."
msgstr ""

#: core/permission_view.py:108
msgid "Permission successfully updated."
msgstr ""

#: core/permission_view.py:140
#, python-format
msgid "There is no permission such permission %(perm_id)s in database"
msgstr ""

#: core/permission_view.py:145
msgid "Permission successfully deleted."
msgstr ""

#: core/phantom_actor.py:52 core/phantom_actor.py:77
msgid "There is no session_token"
msgstr ""

#: core/phantom_actor.py:58 core/phantom_actor.py:83
msgid "There is no such actor"
msgstr ""

#: core/phantom_actor.py:89
msgid "Invalid request data"
msgstr ""

#: core/phantom_actor.py:157
msgid "Phantom relation successfully created."
msgstr ""

#: core/phantom_actor.py:192
msgid "There is no such phantom relation."
msgstr ""

#: core/phantom_actor.py:202
msgid "Phantom relation successfully deleted."
msgstr ""

#: core/service_view.py:406
msgid "Error with updating password. There is no such actor."
msgstr ""

#: core/socket_events.py:40
msgid "Some error occurred while getting socket id."
msgstr ""

#: core/socket_events.py:48
msgid "There is no session token."
msgstr ""

#: core/utils.py:464
msgid "You are in ban group. Please contact the administrator to set you role."
msgstr ""

#: core/actions/phantom_actions.py:45
msgid "Invalid phantom relation unique identifier."
msgstr ""

#: core/actions/phantom_actions.py:51
msgid "Invalid phantom actor data type. Should be unique identifier."
msgstr ""

#: core/actions/phantom_actions.py:58
msgid "Invalid target phantom actor data type. Should be unique identifier."
msgstr ""

#: core/actions/phantom_actions.py:64
msgid "You can't use this function."
msgstr ""

#: core/templates/auth.html:26
msgid "Services"
msgstr ""

#: core/templates/auth.html:62 core/templates/auth.html:79
msgid "English"
msgstr ""

#: core/templates/auth.html:93
msgid "Russian"
msgstr ""

#: core/templates/auth.html:98 core/templates/auth.html:116
msgid "Comming Soon..."
msgstr ""

#: core/templates/auth.html:111
msgid "Chinese"
msgstr ""

#: core/templates/auth.html:117
msgid "Use other language please. We are working on translation"
msgstr ""

#: core/templates/auth.html:134
msgid "Welcome to EcoSystem 54 based service"
msgstr ""

#: core/templates/auth.html:135
msgid "Please, choose the option you need"
msgstr ""

#: core/templates/auth.html:149 core/templates/auth.html:293
msgid "Sign In"
msgstr ""

#: core/templates/auth.html:162 core/templates/auth.html:407
msgid "Sign Up"
msgstr ""

#: core/templates/auth.html:174
msgid "Help Me"
msgstr ""

#: core/templates/auth.html:180
msgid "1. Download application"
msgstr ""

#: core/templates/auth.html:181
msgid "First of all you need to download EcoSystem 54 application."
msgstr ""

#: core/templates/auth.html:184
msgid "Android"
msgstr ""

#: core/templates/auth.html:189
msgid "iPhone"
msgstr ""

#: core/templates/auth.html:198
msgid "2. Create an account"
msgstr ""

#: core/templates/auth.html:200
msgid "Create a new EcoSystem 54 account via sign up form or scanning QR code."
msgstr ""

#: core/templates/auth.html:206
msgid "3. Contact your administrator"
msgstr ""

#: core/templates/auth.html:213
msgid "Account Verification"
msgstr ""

#: core/templates/auth.html:214
msgid ""
"After the registration process, you do not have any rights to view / "
"create / delete content. After your confirmation, the administrator will "
"assign you personal access."
msgstr ""

#: core/templates/auth.html:218
msgid ""
"You have been successfully registered. Please contact your administrator "
"to define your role and get an access to the system."
msgstr ""

#: core/templates/auth.html:224
msgid "4. So easy to use"
msgstr ""

#: core/templates/auth.html:231
msgid "What is Profile service?"
msgstr ""

#: core/templates/auth.html:232
msgid ""
"Profile service is the right palce where you can add/change you personal "
"information. In additional to this, you can also check you personal list "
"of permissions."
msgstr ""

#: core/templates/auth.html:236
msgid ""
"As soon as administrator grants access, profile service will be available"
" for you."
msgstr ""

#: core/templates/auth.html:237
msgid "Go to Profile service"
msgstr ""

#: core/templates/auth.html:256
msgid "Login/Password"
msgstr ""

#: core/templates/auth.html:269 core/templates/auth.html:366
msgid "QR code"
msgstr ""

#: core/templates/auth.html:275
msgid "Sign into your EcoSystem 54 account via sign in form"
msgstr ""

#: core/templates/auth.html:279 core/templates/auth.html:387
msgid "E-mail"
msgstr ""

#: core/templates/auth.html:280 core/templates/auth.html:388
msgid "Enter email"
msgstr ""

#: core/templates/auth.html:283 core/templates/auth.html:393
msgid "Password"
msgstr ""

#: core/templates/auth.html:284 core/templates/auth.html:394
msgid "Enter password"
msgstr ""

#: core/templates/auth.html:298
msgid "Or"
msgstr ""

#: core/templates/auth.html:308
msgid "Sign In with AUTH service"
msgstr ""

#: core/templates/auth.html:315
msgid "Single Sign-On - Technology to sign in by Auth service session."
msgstr ""

#: core/templates/auth.html:323
msgid "Sign into your EcoSystem 54 account by scanning QR code"
msgstr ""

#: core/templates/auth.html:328 core/templates/auth.html:420
msgid "Get a new QR code"
msgstr ""

#: core/templates/auth.html:353
msgid "Register form"
msgstr ""

#: core/templates/auth.html:373
msgid "Create a new EcoSystem 54 account via sign up form"
msgstr ""

#: core/templates/auth.html:377
msgid "First name"
msgstr ""

#: core/templates/auth.html:378
msgid "Enter first name"
msgstr ""

#: core/templates/auth.html:381
msgid "Surname"
msgstr ""

#: core/templates/auth.html:382
msgid "Enter surname"
msgstr ""

#: core/templates/auth.html:397 core/templates/auth.html:398
msgid "Confirm password"
msgstr ""

#: core/templates/auth.html:414
msgid "Create a new EcoSystem 54 account by scanning QR code"
msgstr ""

#~ msgid "Wrong data"
#~ msgstr ""

#~ msgid "Signature verification failed"
#~ msgstr ""

#~ msgid "Error with creating actor"
#~ msgstr ""

#~ msgid "Actor successfully created"
#~ msgstr ""

#~ msgid "Actors successfully updated"
#~ msgstr ""

#~ msgid "Actors successfully deleted"
#~ msgstr ""

#~ msgid "Some error occurred while getting service info"
#~ msgstr ""

#~ msgid "Wrong data was sent."
#~ msgstr ""

#~ msgid "There is no token. Please try again or contact the administrator."
#~ msgstr ""

#~ msgid "Invalid data in token. Please try again or contact the administrator."
#~ msgstr ""

#~ msgid ""
#~ "Some error occurred while creating user."
#~ " Please try again or contact the "
#~ "administrator."
#~ msgstr ""

#~ msgid "Session token successfully created."
#~ msgstr ""

#~ msgid "Some error occurred while creating verification data."
#~ msgstr ""

#~ msgid "Some error occurred with admin group"
#~ msgstr ""

#~ msgid "Can not be such default group"
#~ msgstr ""

#~ msgid ""
#~ "Some error occurred while user "
#~ "registration. Please contact the "
#~ "administrator."
#~ msgstr ""

#~ msgid "User with such email already exists."
#~ msgstr ""

#~ msgid "Your email is invalid. Please check it."
#~ msgstr ""

#~ msgid "Error with recognizing auth service."
#~ msgstr ""

#~ msgid ""
#~ "Some error occurred while creating user."
#~ " Please try again or contact the "
#~ "administrator"
#~ msgstr ""

#~ msgid "User with such email address is already exists."
#~ msgstr ""

#~ msgid "Wrong data format."
#~ msgstr ""

#~ msgid "Wrong optional data. Invalid parameters."
#~ msgstr ""

#~ msgid "Some error occurred while creating user. Please try again"
#~ msgstr ""

#~ msgid "You are successfully got your token."
#~ msgstr ""

#~ msgid ""
#~ "You have no important verification data"
#~ " in your account. Please contact the"
#~ " administrator."
#~ msgstr ""

#~ msgid "There is no such user. Please contact the administrator"
#~ msgstr ""

#~ msgid ""
#~ "Some error occurred with getting your"
#~ " token. Please try again or contact"
#~ " the administrator."
#~ msgstr ""

#~ msgid ""
#~ "Some error occurred while user creating."
#~ " Please try again or contact the "
#~ "administrator."
#~ msgstr ""

#~ msgid "You token is invalid. Please contact the administrator."
#~ msgstr ""

#~ msgid "Your token is invalid. Please try again or contact the administrator."
#~ msgstr ""

#~ msgid "There is no such user. Please try again or contact the administrator."
#~ msgstr ""

#~ msgid ""
#~ "Some error occurred while session "
#~ "creating. Please try again or contact"
#~ " the administrator."
#~ msgstr ""

#~ msgid "User with such email not found."
#~ msgstr ""

#~ msgid "Invalid request type"
#~ msgstr ""

#~ msgid "Session token saved"
#~ msgstr ""

#~ msgid "User have no session token"
#~ msgstr ""

#~ msgid "User have no session"
#~ msgstr ""

#~ msgid "User have no session or APT54"
#~ msgstr ""

#~ msgid "User not found"
#~ msgstr ""

#~ msgid "User is banned"
#~ msgstr ""

#~ msgid "There is no such user"
#~ msgstr ""

#~ msgid "Permissions denied"
#~ msgstr ""

#~ msgid "Unsupported Media Type"
#~ msgstr ""

#~ msgid "Database error"
#~ msgstr ""

#~ msgid "User apt54 expired! You need update it."
#~ msgstr ""

#~ msgid "Error with getting salt"
#~ msgstr ""

#~ msgid "Error with getting apt54"
#~ msgstr ""

#~ msgid "Error with getting session"
#~ msgstr ""

#~ msgid "Invalid service class"
#~ msgstr ""

#~ msgid "Auth service is unavailable"
#~ msgstr ""

#~ msgid "Error with sending request"
#~ msgstr ""

#~ msgid "Static group is missing"
#~ msgstr ""

#~ msgid "Wrong service type"
#~ msgstr ""

#~ msgid "Invalid request params"
#~ msgstr ""

#~ msgid "Error with saving data in database"
#~ msgstr ""

#~ msgid "Permissions successfully updated"
#~ msgstr ""

#~ msgid "Permission successfully deleted"
#~ msgstr ""

#~ msgid "Phantom relation successfully created"
#~ msgstr ""

#~ msgid "There is no such phantom object"
#~ msgstr ""

#~ msgid "Phantom relation successfully deleted"
#~ msgstr ""

#~ msgid "Error with getting socket id"
#~ msgstr ""

#~ msgid "There is no session token"
#~ msgstr ""

#~ msgid "Invalid uuid value"
#~ msgstr ""

#~ msgid "Invalid data value"
#~ msgstr ""

#~ msgid "Invalid data target actor"
#~ msgstr ""

#~ msgid "You can not use this"
#~ msgstr ""

#~ msgid "Use English. We are working on translation"
#~ msgstr ""

